# Generated by Django 3.2.18 on 2023-06-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='標籤名稱')),
                ('Note', models.TextField(blank=True, null=True, verbose_name='備註')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='Tag',
            field=models.ManyToManyField(to='main.Tag', verbose_name='標籤'),
        ),
    ]
