# Generated by Django 3.2.19 on 2023-06-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Internet',
            field=models.BooleanField(default=True, verbose_name='可否上網'),
        ),
    ]
