# Generated by Django 3.2.19 on 2023-06-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinfo_internet'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Internet',
            field=models.BooleanField(default=True, verbose_name='可否上網'),
        ),
    ]
