# Generated by Django 3.2.19 on 2023-06-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230602_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='裝置名稱'),
        ),
    ]
