# Generated by Django 3.2.19 on 2023-06-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group_internet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Class',
            field=models.IntegerField(default=0, verbose_name='班級'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Grade',
            field=models.IntegerField(choices=[(0, '無'), (7, '七年級'), (8, '八年級'), (9, '九年級'), (1, '高一'), (2, '高二'), (3, '高三')], default=0, verbose_name='年級'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='SeatNumber',
            field=models.IntegerField(default=0, verbose_name='座號'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='StuId',
            field=models.IntegerField(default=0, verbose_name='學號'),
        ),
    ]
